name: SYMBOLIC-GOSSIP-FP
version: 0.1.0.0
synopsis: Functional Programming 2024 - Symbolic Gossip Project
description: See report.pdf
maintainer: Wouter Smit <pathemeous@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - smcdel
  - HasCacBDD
  - tagged
  - directory
  - process
  - criterion

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - SYMBOLIC-GOSSIP-FP

tests:
  testsuite:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - SYMBOLIC-GOSSIP-FP
      - QuickCheck
      - hspec

benchmarks:
  bench:
    main: trfBenchmarks.lhs
    source-dirs: bench
    dependencies:
      - SYMBOLIC-GOSSIP-FP
      - criterion